### PR TITLE
Added 'runtime' flag for codesign command

### PR DESCRIPTION
**Pull request by divyeshmakwana96**

### CODE REVIEW

**Comment by xndrs** [comment]
Hi @divyeshmakwana96 , thanks for the contribution. 
Can you please explain what problem this flag solves or the feature it supports?

**Comment by divyeshmakwana96** [comment]
@xndrs Hi Alex, my bad. I thought I linked Issue #32. To elaborate further, Apple recently introduced a more secure signature format for iOS. You can read more about it [here](https://developer.apple.com/documentation/xcode/using-the-latest-code-signature-format) starting iOS 14.2. With iOS 15, they have made a mandatory requirement that all the apps must be signed using the new secure format. If the IPA still contains old signature format, the app won't launch and will display a popup mentioned in the thread [here](https://developer.apple.com/forums/thread/682775). This problem is exclusive to non App Store deployment only.

The document suggests that using the latest macOS BigSur and Xcode should take care of the problem, but it doesn't seem to be the case always. To check wether an app is signed using new signature, following command:

`% codesign -dv /path/to/MyApp.app`

From Apple's document, the new signature format will contain `CodeDirectory v=20500`. In order for this to happen, `codesign` requires runtime flag. I believe this issue might be more prominent with the public release of iOS 15.

**Comment by xndrs** [comment]
@divyeshmakwana96, thanks for the explanation. But following the [thread](https://developer.apple.com/forums/thread/682775) you mentioned, this flag does not help solve the problem. You can see about this in the next post (in the same thread). People talk more about renewed provisioning profiles, upgraded Xcode and additional flag **"--generate-entitlement-der"**.

Also look at [this](https://stackoverflow.com/questions/68467306/the-code-signature-version-is-no-longer-supported), another post about same problem, where talking about **"--generate-entitlement-der"** flag.

Hm, this is an interesting point with the change in code signing behavior. 
Did using the flag **"--options runtime"** help you solve this problem?

**Comment by divyeshmakwana96** [comment]
@xndrs Actually I tried the `--generate-entitlement-der` flag and it still didn't fix CodeDirectory v=20200. In my case only `--options runtime` seem to update the signature to the latest code signing. I am actually working with an enterprise deployment team to verify wether it fixes the iOS 15 "update popup", but most certainly it fixed the CodeDirectory version requirement.

**Comment by xndrs** [comment]
@divyeshmakwana Understood. Could you verify if it actually solves the installation issue on iOS 15 ? 
Apple's documentation suggests using this flag `-options runtime` to enable a hardened runtime, for example during the notarization process for macOS apps you can get an error if it's not enabled.
I totally agree with you that this flag can cause the CodeDirectory value to be updated. But the question is whether this solves the installation problem.

**Comment by xndrs** [comment]
btw, same installation issue with iOS 15 exists not only with enterprise distribution. default ad hoc distribution has the same installation issue

**Comment by divyeshmakwana96** [comment]
@xndrs Alright so I investigate and found out the issue. The App Store distribution certificate always outputs `CodeDirectory v=20200`. However when I tried signing using a new Ad Hoc certificate the code signature was `CodeDirectory v=20400`. I think apple did it on purpose to avoid third party signing on App Store apps.

Below are two of scenarios that I tested for the ipa signed with the App Store distribution certificate:
1) Resign with Ad Hoc - Didn't install
2) Resign with Ad Hoc (runtime option) - Did install, but crashes on launch

May be Apple wants to restrict App Store apps signed by third party.

**Comment by xndrs** [comment]
@divyeshmakwana96 Thanks for your investigation. It's greatly appreciated !! Unfortunately, as you see, this option (`--options runtime`) will not solve the issue. I close the merge request, but your issue's [ticket](https://github.com/xndrs/XReSign/issues/32) remain opened. Thanks again!!!

**Pull request closed without merging**
