### PR TITLE
Add entitlements from IPA

### PR DESCRIPTION
**Pull request by csc-EricWu**

### CODE REVIEW

**Comment by csc-EricWu** [comment]
I resolved the conflict

**Comment by csc-EricWu** [comment]
I made some changes to make it easier for him to use.

**Comment by xndrs** [comment]
> I made some changes to make it easier for him to use.

what problem does this solve?
you can see that entitlements from IPA and outside from it just supported in the script: [xresign.sh](https://github.com/xndrs/XReSign/blob/5acd23ff21d00ef7889eb3e4cc7689527fbb0205/XReSign/Scripts/xresign.sh#L67)

**Comment by csc-EricWu** [comment]
Get permissions through IPA or mobileprovision and edit them. for example com.apple.developer . associated domains, want real entitlements instead of "*"

**Pull request closed without merging**
